language: java
jdk:
  - openjdk8

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: lsp-admin

before_install:
  - chmod +x mvnw

after_success:
  - mvn jacoco:report coveralls:report